{
 "title": "Infrastructure Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance,job) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_memory_Active_bytes/node_memory_MemTotal_bytes*100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/etc/hosts\"} - node_filesystem_avail_bytes{mountpoint=\"/etc/hosts\"}) / node_filesystem_size_bytes{mountpoint=\"/etc/hosts\"} * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Disk Usage GBs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/etc/hosts\"} / 1024^3 - node_filesystem_avail_bytes{mountpoint=\"/etc/hosts\"} / 1024^3",
     "legendFormat": "used disk space ({{job}})"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/etc/hosts\"} / 1024^3",
     "legendFormat": "disk size ({{job}})"
    }
   ]
  }
 ]
}